# Generated by Django 5.0.3 on 2025-10-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
