# Generated by Django 5.0.3 on 2025-10-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0005_fridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fridge_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appbackend.fridge'),
            preserve_default=False,
        ),
    ]
